apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weechat-logs-storage
  namespace: weechat
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi